dofile("C:/Users/servernoroot/Saved Games/dcs-kellergeschwader-missions/server-syria/operation-steadfast-syria/logic/CTLD_Steadfast.lua")
dofile("C:/Users/servernoroot/Saved Games/dcs-kellergeschwader-missions/server-syria/operation-steadfast-syria/logic/Hercules_Cargo_CTLD.lua")
dofile("C:/Users/servernoroot/Saved Games/dcs-kellergeschwader-missions/server-syria/operation-steadfast-syria/logic/border-war/Steadfast_Border_War.lua")
dofile("C:/Users/servernoroot/Saved Games/dcs-kellergeschwader-missions/server-syria/operation-steadfast-syria/logic/AWACS_Air_Respawn.lua")
dofile("C:/Users/servernoroot/Saved Games/dcs-kellergeschwader-missions/server-syria/operation-steadfast-syria/logic/Jordan/Jordan.lua")
dofile("C:/Users/servernoroot/Saved Games/dcs-kellergeschwader-missions/server-syria/operation-steadfast-syria/logic/Steadfast_AI_Balancer.lua")
