dofile(missionDir .. "logic\\CTLD_Steadfast.lua")
dofile(missionDir .. "logic\\Hercules_Cargo_CTLD.lua")
dofile(missionDir .. "logic\\Steadfast_ScriptingFunctions.lua")
dofile(missionDir .. "logic\\Steadfast_SpawnDefs.lua")
dofile(missionDir .. "logic\\AWACS_Air_Respawn.lua")
dofile(missionDir .. "logic\\AA_Defense_Jordan.lua")
dofile(missionDir .. "logic\\Steadfast_AI_Balancer.lua")