dofile(missionDir .. "logic\\CTLD_Steadfast.lua")
dofile(missionDir .. "logic\\Hercules_Cargo_CTLD.lua")
dofile(missionDir .. "logic\\border-war\\Steadfast_Border_War.lua")
dofile(missionDir .. "logic\\AWACS_Air_Respawn.lua")
dofile(missionDir .. "logic\\Jordan\\Jordan.lua")
dofile(missionDir .. "logic\\Steadfast_AI_Balancer.lua")